name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ['armv7hl', 'aarch64', 'i486']

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: prepare
      run: mkdir RPMS

    - name: Build ${{ matrix.arch }}
      run: docker run --rm --privileged -v $PWD:/workspace registry.gitlab.com/whisperfish/sailo-rs/rust-${{ matrix.arch }}-$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            mb2 -t SailfishOS-$RELEASE-${{ matrix.arch }} build ;
            cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Upload build result
      uses: actions/upload-artifact@v5
      with:
        name: rpms
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

