name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: prepare
      run: mkdir RPMS

    - name: Build armv7hl
      run: docker run --rm --privileged -v $PWD:/workspace registry.gitlab.com/whisperfish/sailo-rs/rust-armv7hl-$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            export OPENSSL_DIR=/usr ;
            sb2 -t SailfishOS-$RELEASE-armv7hl -m sdk-build cargo build --release --target armv7-unknown-linux-gnueabihf --target-dir rust/target --manifest-path rust/Cargo.toml --locked ;
            mb2 -t SailfishOS-$RELEASE-armv7hl build ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Build aarch64
      run: docker run --rm --privileged -v $PWD:/workspace registry.gitlab.com/whisperfish/sailo-rs/rust-aarch64-$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            export OPENSSL_DIR=/usr ;
            sb2 -t SailfishOS-$RELEASE-aarch64 -m sdk-build cargo build --release --target aarch64-unknown-linux-gnu --target-dir rust/target --manifest-path rust/Cargo.toml --locked ;
            mb2 -t SailfishOS-$RELEASE-aarch64 build ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Build i486
      run: docker run --rm --privileged -v $PWD:/workspace registry.gitlab.com/whisperfish/sailo-rs/rust-i486-$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            export OPENSSL_DIR=/usr ;
            sb2 -t SailfishOS-$RELEASE-i486 -m sdk-build cargo build --release --target i686-unknown-linux-gnu --target-dir rust/target --manifest-path rust/Cargo.toml --locked ;
            mb2 -t SailfishOS-$RELEASE-i486 build ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Upload build result
      uses: actions/upload-artifact@v5
      with:
        name: rpms
        path: RPMS
